// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ReverseIntake.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ReverseIntake::ReverseIntake(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pickupRoller.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ReverseIntake::Initialize() {
    SetTimeout(0.5);
    Robot::pickupRoller->RunOut();
}

// Called repeatedly when this Command is scheduled to run
void ReverseIntake::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool ReverseIntake::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void ReverseIntake::End() {
	Robot::pickupRoller->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ReverseIntake::Interrupted() {
    End();
}
