// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "CmdAutonomous.h"
#include "Commands/CmdLaunchFuel.h"
#include "Commands/CmdAutoDrive.h"
#include "Commands/CmdAutoMotorTest.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdAutonomous::CmdAutonomous() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.

	AddParallel(new CmdAutoMotorTest());
	AddSequential(new CmdAutoDrive(0.2, 0.0, 1));	//Drive Forward for 1 second
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause for 2 seconds
	AddSequential(new CmdAutoDrive(0.2, 0.5, 1));	//Turn Right
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause
	AddSequential(new CmdAutoDrive(0.2, -0.5, 1));	//Turn Left
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause
	AddSequential(new CmdAutoDrive(0.2, 1.0, 1));	//Turn On Spot (clockwise)
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause
	AddSequential(new CmdAutoDrive(0.2, -1.0, 1));	//Turn On Spot (anti-clockwise)
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause
	AddSequential(new CmdAutoDrive(0.5, 0.25, 1));	//Turn (slowly)
	AddSequential(new CmdAutoDrive(0.0, 0.0, 2));	//Pause
	AddSequential(new CmdAutoDrive(0.5, 0.75, 1));	//Turn (slowly)

              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

              // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
