// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CMDAUTODRIVE_H
#define CMDAUTODRIVE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "PIDController.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class CmdAutoDrive: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	CmdAutoDrive(double Power, double Direction, double Duration);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    double m_Power;
    double m_Direction;
    double m_Duration;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
    double p_constant;
    double i_constant;
    double d_constant;

    PIDController*  myController;
    /*
    int count;
    double angle;
    double correction;
    */
};

#endif
