// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "CmdAuto4DeployGearFromLeft.h"
#include "CmdAutoDrive.h"
#include "CmdAutoTurn.h"
#include "CmdAutoDriveToPeg.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdAuto4DeployGearFromLeft::CmdAuto4DeployGearFromLeft() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.

	//Auto 4: Drive Forward, turn left toward peg, drive toward peg
	AddSequential(new CmdAutoDrive(-0.3, 0, 2.5));
	// AddSequential(new CmdAutoTurn(0, 0.25, 30));
	AddSequential(new CmdAutoTurn(0, 0.3, 30));
	AddSequential(new CmdAutoDrive(0,0,1.5)); // pause for a second (to make sure imaging is capturing the target)
	AddSequential(new CmdAutoTurn(1, 0.3, 0));
	AddSequential(new CmdAutoDrive(0,0,0.5)); // pause for a second (just so that we can see if there is a correction)
	AddSequential(new CmdAutoDrive(-0.3, 0, 2.5));
	//AddSequential(new CmdAutoDriveToPeg());
	//AddSequential(new CmdAutoDrive(0.0, 0.0, 3.0));
	//AddSequential(new CmdAutoTurn(0.4, -60));
	//AddSequential(new CmdAutoDrive(0.3, 0, 1.5));

              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
              // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
