// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "CmdAutonomous.h"
#include "Commands/CmdLaunchFuel.h"
#include "Commands/CmdAutoDrive.h"
#include "Commands/CmdAutoTurn.h"
#include "Commands/CmdAutoDriveToPeg.h"
#include "Commands/CmdAutoMotorTest.h"

#include "Commands/CmdAuto2ShootGoals.h"
#include "Commands/CmdAuto3DeployGearFromRight.h"
#include "Commands/CmdAuto4DeployGearFromLeft.h"
#include "Commands/CmdAuto5MotionProfileToLeftPeg.h"
#include "Commands/CmdAuto7MotionProfileToMidPeg.h"
#include "Commands/CmdAuto6MotionProfileToRightPeg.h"
#include "Commands/CmdAuto8MotionProfileToBaseline.h"
#include "Commands/CmdAuto9DoNothing.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdAutonomous::CmdAutonomous() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	/* Add Commands here:
    e.g. AddSequential(new Command1());
         AddSequential(new Command2());
    these will run in order.

    To run multiple commands at the same time, use AddParallel()
    e.g. AddParallel(new Command1());
         AddSequential(new Command2());
    Command1 and Command2 will run in parallel.

    A command group will require all of the subsystems that each member
    would require.
    e.g. if Command1 requires chassis, and Command2 requires arm,
    a CommandGroup containing them would require both the chassis and the
    arm. */

	if( Robot::subDriveBase->IsDIOChannel06on() )
	{
		AddSequential(new CmdAuto5MotionProfileToLeftPeg);
	}
	else if ( Robot::subDriveBase->IsDIOChannel07on()) {
		AddSequential(new CmdAuto7MotionProfileToMidPeg);
	}
	else if ( Robot::subDriveBase->IsDIOChannel08on()) {
		AddSequential(new CmdAuto6MotionProfileToRightPeg);
	}
	else if ( Robot::subDriveBase->IsDIOChannel09on()) {
		AddSequential(new CmdAuto8MotionProfileToBaseline);
	}
	else {
		AddSequential(new CmdAuto9DoNothing);
	}

              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

              // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
