// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CmdAutoDrive.h"
#include "..\Custom\DrivePIDOutput.h"
#include "..\Custom\GyroPIDSource.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdAutoDrive::CmdAutoDrive(double Power, double Direction, double Duration): Command() {
    m_Power = Power;
    m_Direction = Direction;
    m_Duration = Duration;
    if( m_Power > 0 )
    {
        p_constant = +5.0;
        i_constant = +0.0;
        d_constant = +10.0;
    }
    else
    {
        p_constant = -5.0;
        i_constant = -0.0;
        d_constant = -10.0;
    }
    myController = new PIDController(p_constant, i_constant, d_constant,static_cast<PIDSource*>( new GyroPIDSource()), new DrivePIDOutput(m_Power));
    myController->SetContinuous(true);
    myController->SetInputRange(-180,+180);
    myController->SetOutputRange(-1,+1);
    myController->SetSetpoint(Direction);
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subDriveBase.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CmdAutoDrive::Initialize() {
	SetTimeout(m_Duration);
	Robot::subDriveBase->ResetAngle();
	myController->Enable();

}

// Called repeatedly when this Command is scheduled to run
void CmdAutoDrive::Execute() {

/*
	count += 1;
	if (count >= 10){
		angle = Robot::subDriveBase->GetAngle();
		correction = -(angle/360);
		count = 0;
	}

	Robot::subDriveBase->Drive(m_Power, m_Direction - correction);
*/
}

// Make this return true when this Command no longer needs to run execute()
bool CmdAutoDrive::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void CmdAutoDrive::End() {
	myController->Disable();
	Robot::subDriveBase->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CmdAutoDrive::Interrupted() {
	End();
}
