// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CmdJoystickDrive.h"
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdJoystickDrive::CmdJoystickDrive(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subDriveBase.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CmdJoystickDrive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void CmdJoystickDrive::Execute() {
	Robot::subDriveBase->TakeJoystickInputs( Robot::oi->getJoystick1() );
//	SmartDashboard::PutNumber("Gyro", Robot::subDriveBase->GetAngle());
    // lets just display the values here to prove that they are actually being
	// set as expected ... this is a pretty useless operation as these values are
	// already available elsewhere in the network tables but it should give us
	// some confidence that we can read from the network tables :)
	SmartDashboard::PutNumber("PegX (extracted from JETSON via network table", Robot::subDriveBase->GetPegX());
	SmartDashboard::PutNumber("PegY (extracted from JETSON via network table)", Robot::subDriveBase->GetPegY());
	SmartDashboard::PutNumber("Drive Left Encoder Position", Robot::subDriveBase->GetLeftEncoderPosition());
	SmartDashboard::PutNumber("Drive Right Encoder Position", Robot::subDriveBase->GetRightEncoderPosition());
}

// Make this return true when this Command no longer needs to run execute()
bool CmdJoystickDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void CmdJoystickDrive::End() {
	Robot::subDriveBase->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CmdJoystickDrive::Interrupted() {
	End();
}
