// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CmdAutoNudgeForward.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdAutoNudgeForward::CmdAutoNudgeForward(): Command() {
    m_Execounter = 0;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subDrivebase.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CmdAutoNudgeForward::Initialize() {
	execounter = 0;
	Robot::subDrivebase->Drive(0.2, 0.147);


}

// Called repeatedly when this Command is scheduled to run
void CmdAutoNudgeForward::Execute() {
	execounter++;
}

// Make this return true when this Command no longer needs to run execute()
bool CmdAutoNudgeForward::IsFinished() {
	if( execounter > 50 )
		{
			return true;
		}
			return false;

}

// Called once after isFinished returns true
void CmdAutoNudgeForward::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CmdAutoNudgeForward::Interrupted() {

}
