// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CmdSideBaseline.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CmdSideBaseline::CmdSideBaseline(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subDrivebase.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CmdSideBaseline::Initialize() {
	execounter = 0;
	Robot::subDrivebase->Drive(-0.5, 0.147);
}

// Called repeatedly when this Command is scheduled to run
void CmdSideBaseline::Execute() {
	execounter++;
}

// Make this return true when this Command no longer needs to run execute()
bool CmdSideBaseline::IsFinished() {
	if( execounter > 400 )
		{
			return true;
		}
			return false;
}

// Called once after isFinished returns true
void CmdSideBaseline::End() {
	Robot::subDrivebase->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CmdSideBaseline::Interrupted() {
	End();
}
