// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CmdJoyStickDrive.h"
#include "Commands/CmdSuck.h"
#include "Commands/CmdSpit.h"
#include "Commands/CmdArmJoy.h"
#include "Commands/CmdArmFront.h"
#include "Commands/CmdArmFrontMid.h"
#include "Commands/CmdArmUp.h"
#include "Commands/CmdArmBackMid.h"
#include "Commands/CmdArmBack.h"
#include "Commands/CmdSpinCube.h"
#include "Commands/CmdLeftIntake.h"
#include "Commands/CmdRightIntake.h"

OI::OI() {
    joystick.reset(new frc::Joystick(0));
    

    //SmartDashboard Buttons
    frc::SmartDashboard::PutData("CmdJoyStickDrive", new CmdJoyStickDrive());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    //Intake
    btnSucker.reset(new JoystickButton(joystick.get(), 5));
    btnSucker->WhileHeld(new CmdSuck());
    btnSpitter.reset(new JoystickButton(joystick.get(), 6));
    btnSpitter->WhileHeld(new CmdSpit());
    btnSpinCube.reset(new JoystickButton(joystick.get(), 9));
    btnSpinCube->WhileHeld(new CmdSpinCube());
    axbLeftIntake.reset(new AxisButton(joystick.get(), 2));
	axbLeftIntake->WhileHeld(new CmdLeftIntake());
    axbRightIntake.reset(new AxisButton(joystick.get(), 3));
    axbRightIntake->WhileHeld(new CmdRightIntake());

    //Arm Controls
    btnManualArm.reset(new JoystickButton(joystick.get(), 10));
    btnManualArm->WhileHeld(new CmdArmJoy());

    btnArmPIDFront.reset(new JoystickButton(joystick.get(), 7));
    btnArmPIDFront->WhileHeld(new CmdArmFront());
    btnArmPIDFrontMid.reset(new JoystickButton(joystick.get(), 1));
    btnArmPIDFrontMid->WhileHeld(new CmdArmFrontMid());
    btnArmPIDUp.reset(new JoystickButton(joystick.get(), 2));
    btnArmPIDUp->WhileHeld(new CmdArmUp());
    btnArmPIDBackMid.reset(new JoystickButton(joystick.get(), 4));
    btnArmPIDBackMid->WhileHeld(new CmdArmBackMid());
    btnArmPIDBack.reset(new JoystickButton(joystick.get(), 8));
    btnArmPIDBack->WhileHeld(new CmdArmBack());
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick() {
   return joystick;
}

double OI::GetLeftAxis() {
	return axbLeftIntake->GetAxis();
}

double OI::GetRightAxis() {
	return axbRightIntake->GetAxis();
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
