// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	
	std::shared_ptr<frc::Joystick> joystick;
	std::shared_ptr<JoystickButton> btnSucker;
	std::shared_ptr<JoystickButton> btnSpitter;
	std::shared_ptr<JoystickButton> btnManualArm;
	std::shared_ptr<JoystickButton> btnArmPIDFront;
	std::shared_ptr<JoystickButton> btnArmPIDBack;

public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getJoystick();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
