// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "FrontArm.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

FrontArm::FrontArm() : Subsystem("FrontArm") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    doubleSolenoidLeft = RobotMap::frontArmDoubleSolenoidLeft;
    doubleSolenoidRight = RobotMap::frontArmDoubleSolenoidRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void FrontArm::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void FrontArm::Up() {
	doubleSolenoidLeft->Set(DoubleSolenoid::Value::kReverse);
	doubleSolenoidRight->Set(DoubleSolenoid::Value::kReverse);
}

void FrontArm::Down() {
	doubleSolenoidLeft->Set(DoubleSolenoid::Value::kForward);
	doubleSolenoidRight->Set(DoubleSolenoid::Value::kForward);
}

void FrontArm::Stop() {
	doubleSolenoidLeft->Set(DoubleSolenoid::Value::kOff);
	doubleSolenoidRight->Set(DoubleSolenoid::Value::kOff);
}
