// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SUBDRIVEBASE_H
#define SUBDRIVEBASE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "CANTalon.h"
// #include <ADXRs450_gyro.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class SubDriveBase: public Subsystem {
private:
	std::shared_ptr<DigitalInput> dioChannel06;
	std::shared_ptr<DigitalInput> dioChannel07;
	std::shared_ptr<DigitalInput> dioChannel08;
	std::shared_ptr<DigitalInput> dioChannel09;

	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> tnxRightMaster;
	std::shared_ptr<CANTalon> tnxLeftMaster;
	std::shared_ptr<RobotDrive> robotDriveTwo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> tnxLeftSlave;
	std::shared_ptr<CANTalon> tnxRightSlave;
//	std::shared_ptr<ADXRS450_Gyro> gyro;
	std::shared_ptr<NetworkTable> jetsonNetworkTable;

public:
	SubDriveBase();
	void InitDefaultCommand();
	void TakeJoystickInputs( std::shared_ptr<Joystick> stick );
	void Drive( double direction, double power );
	double GetLeftEncoderPosition();
	double GetRightEncoderPosition();
//	double GetAngle();
	void Stop();
//	void ResetAngle();
	double GetPegX();
	double GetPegY();
	double GetPegRange();
	double GetPegWidth();
	double GetEncoderLeft;
	double GetEncoderRight;
	bool IsDIOChannel06on();
	bool IsDIOChannel07on();
	bool IsDIOChannel08on();
	bool IsDIOChannel09on();

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
