// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SUBINTAKE_H
#define SUBINTAKE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class SubIntake: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> tnxIntakeRollers;
	std::shared_ptr<CANTalon> tnxIntakeSliders;
	std::shared_ptr<DigitalInput> lswSliderIn;
	std::shared_ptr<DigitalInput> lswSliderOut;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	SubIntake();
	void InitDefaultCommand();
	void RollerIn();
	void RollerOut();
	void RollerOff();
	void SliderIn();
	void SliderOut();
	void SliderOff();
	bool IsSliderOut();
	bool IsSliderIn();



	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};


#endif
