// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CANTalon.h"


#include "SubShooter.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

SubShooter::SubShooter() : Subsystem("SubShooter") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    tnxShooterTop = RobotMap::subShooterTnxShooterTop;
    tnxShooterBottom = RobotMap::subShooterTnxShooterBottom;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void SubShooter::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void SubShooter::Run() {
    // tnxShooterTop->Set(0.67);
    // tnxShooterBottom->Set(-0.3);

	// for PID setup we use power values in the set commands ...
	//tnxShooterTop->SetControlMode(CANSpeedController::kPercentVbus);
    //tnxShooterBottom->SetControlMode(CANSpeedController::kPercentVbus);
	//tnxShooterTop->Set(1.0);
    //tnxShooterBottom->Set(1.0);

    // if mode is kSpeed then the we use RPM values in the set commands ...
	tnxShooterTop->SetControlMode(CANSpeedController::kSpeed);
	tnxShooterBottom->SetControlMode(CANSpeedController::kSpeed);
	tnxShooterTop->Set(6000);
    tnxShooterBottom->Set(-1000);
}

void SubShooter::Stop() {
    tnxShooterTop->SetControlMode(CANSpeedController::kPercentVbus);
    tnxShooterBottom->SetControlMode(CANSpeedController::kPercentVbus);
	tnxShooterTop->Set(0);
    tnxShooterBottom->Set(0);
}

double SubShooter::GetTopEncoderSpeed() {
    return tnxShooterTop->GetSpeed();
}

double SubShooter::GetBottomEncoderSpeed() {
    return tnxShooterBottom->GetSpeed();
}
