// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/cmdClimb.h"
#include "Commands/cmdLaunchFuel.h"
#include "Commands/cmdMoveServo.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick1.reset(new Joystick(0));
    
    btnLaunchFuel.reset(new JoystickButton(joystick1.get(), 12));
    btnLaunchFuel->WhileHeld(new cmdLaunchFuel());
    btnClimb.reset(new JoystickButton(joystick1.get(), 2));
    btnClimb->WhileHeld(new cmdClimb());
    btnMoveServo.reset(new JoystickButton(joystick1.get(), 1));
    btnMoveServo->WhileHeld(new cmdMoveServo());

    // SmartDashboard Buttons
    SmartDashboard::PutData("cmdLaunchFuel", new cmdLaunchFuel());
    SmartDashboard::PutData("cmdClimb", new cmdClimb());
    SmartDashboard::PutData("cmdMoveServo", new cmdMoveServo());
    SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystick1() {
   return joystick1;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
